import {Organizations} from "@/api/types";

export const defaultOrg: Organizations = {
  id: '',
  code: '',
  name: '',
  fullName: '',
  parentId: '',
  parentName: '',
  type: '',
  codePath: '',
  namePath: '',
  level: '0',
  hasChild: '',
  division: '',
  country: '',
  region: '',
  locality: '',
  street: '',
  address: '',
  contact: '',
  postalCode: '',
  phone: '',
  fax: '',
  email: '',
  sortIndex: '0',
  description: '',
  sortOrder: '',
  status: '1',
  createdBy:'',
  createdDate:'',
  modifiedBy:'',
  modifiedDate:''
}
